# este archivo YAML define el workflow de GitHub Actions para ejecutar un escaneo de seguridad utilizando OWASP ZAP. El workflow se activa cada vez que se realiza un push al repositorio. El proceso incluye la instalación de OWASP ZAP, la ejecución del escaneo definido en zap_scan.yaml, y la subida del reporte generado como un artefacto para su revisión posterior.
name: ZAP Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar OWASP ZAP
        run: sudo apt-get update && sudo apt-get install -y zaproxy

      - name: Comprobamos estoado de máquina y por si acaso paramos Juice-Shop para que no de error
        run: docker stop pps-juice-shop

      - name: Levantar contenedor de  Juice-Shop
        run: docker start pps-juice-shop

      - name: Ejecutar escaneo
        run: |
          zaproxy -cmd -autorun zap_scan.yaml

      - name: Subir reporte
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: zap_report.html

      - name: Parar contenedor
        run: docker stop pps-juice-shop
