# este archivo YAML define el workflow de GitHub Actions para ejecutar un escaneo de seguridad utilizando OWASP ZAP. El workflow se activa cada vez que se realiza un push al repositorio. El proceso incluye la instalación de OWASP ZAP, la ejecución del escaneo definido en zap_scan.yaml, y la subida del reporte generado como un artefacto para su revisión posterior.
name: zap_scan.yml

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start target app
        run: |
          docker run -d --name juidce-shop --rm -p 3000:3000 bkimminich/juice-shopd
          sleep 5

      - name: Run ZAP Automation Plan
        run: |
          PWD=$(pwd) docker run --network="host" \
            -v $(pwd):/zap/wrk \
            owasp/zap2docker-stable \
            zap.sh -cmd -autorun /zap/wrk/zap-plan.yaml

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
